import { Result } from '@/src/result';
import { ResultAsync } from '../../src';

describe('Result', () => {
  describe('bindFailureAsync', () => {
    describe('Promise', () => {
      test('takes the result from the second result, when previous result fails', async () => {
        const sut = Result.failure('ğŸ’¥');

        const innerResult = await sut
          .bindFailureAsync(() => Promise.resolve(Result.success('âœ…')))
          .toPromise();

        return expect(innerResult).toSucceedWith('âœ…');
      });

      test('takes the result from the first result, when it succeeds', async () => {
        const sut = Result.success('âœ…');

        const innerResult = await sut
          .bindFailureAsync(() => Promise.resolve(Result.failure('ğŸ’¥')))
          .toPromise();

        return expect(innerResult).toSucceedWith('âœ…');
      });

      test('takes the failure from the second result, when both fail', async () => {
        const sut = Result.failure('ğŸ’¥');

        const innerResult = await sut
          .bindFailureAsync(() => Promise.resolve(Result.failure('ğŸ’¥ğŸ’¥')))
          .toPromise();

        return expect(innerResult).toFailWith('ğŸ’¥ğŸ’¥');
      });
    });

    describe('ResultAsync', () => {
      test('takes the result from the second result, when previous result fails', async () => {
        const sut = Result.failure('ğŸ’¥');

        const innerResult = await sut
          .bindFailureAsync(() => ResultAsync.success('âœ…'))
          .toPromise();

        return expect(innerResult).toSucceedWith('âœ…');
      });

      test('takes the result from the first result, when it succeeds', async () => {
        const sut = Result.success('âœ…');

        const innerResult = await sut
          .bindFailureAsync(() => ResultAsync.failure('ğŸ’¥'))
          .toPromise();

        return expect(innerResult).toSucceedWith('âœ…');
      });

      test('takes the failure from the second result, when both fail', async () => {
        const sut = Result.failure('ğŸ’¥');

        const innerResult = await sut
          .bindFailureAsync(() => ResultAsync.failure('ğŸ’¥ğŸ’¥'))
          .toPromise();

        return expect(innerResult).toFailWith('ğŸ’¥ğŸ’¥');
      });
    });
  });
});
